config/routes.rb
Rails.application.routes.draw do
  # booksにアクセスしたらbooksコントローラーのトップアクションを呼ぶ
  get 'books' => 'books#top', as: 'top'
  # 'books#show'の設定をshow_path(book.id)として利用できるようにする
  get 'books/:id' => 'books#show', as: 'show'

  get 'books/:id/edit' => 'books#edit', as: 'edit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # HTTPメソッド 'URL' => 'コントローラ#アクション'
  # トップページをルートにするroot to: 'コントローラ#アクション'
  root to: 'toppage#top'

  post 'books' => 'books#create'

  patch 'books/:id/edit' => 'books#update'

  delete 'books/:id' => 'books#destroy', as: 'destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title,
    presence: true

  validates :body,
    presence: true
end
# モデル名はコントローラー名と対応させる、またモデルは一つの為単数形、コントローラーは中にアクションがたくさんあるから複数形となる。
# モデルのなかのスキーマは設定を見ることができる。変だったらリセットすることができる
# rails db:migrate:reset

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def top
    @book = Book.new
    @books = Book.all
  end

  def create
    # strongパラメータを使用する
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "投稿成功!"
      redirect_to show_path(@book.id)
    else
      flash[:notice] = "投稿失敗したやで"
      @books = Book.all
      render action: :top
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      flash[:notice] = "編集成功!"
      redirect_to show_path(book.id)
    else
      @book = Book.find(params[:id])
      flash[:notice] = "編集失敗したやで"
      render action: :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "削除成功!"

    redirect_to top_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/toppage_controller.rb
class ToppageController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/toppage_helper.rb
module ToppageHelper
end

app/views/books/edit.html.erb
<% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
<% end %>
<h1>Editing Book</h1>
<!-- url:とmethod:を加えることで無理やり指定するmethodは不要かも -->
<%= form_for(@book, url: {action: "update"}, method: :patch) do |f| %>
  <!-- バリデーションエラーを表示させる -->
  <% if @book.errors.any? %>
    <p>入力した内容にエラーが<%= @book.errors.count %>件あります</p>
    <ul>
      <% @book.errors.full_messages.each do |book_error| %>
        <li><%= book_error %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :title, "title" %>
  <%=  f.text_field :title, class:"book_title" %>

  <%= f.label :body, "Body" %>
  <%= f.text_area :body, class:"book_body" %>

  <%= f.submit 'Update Book' %>

<% end %>

<%= link_to 'Show', show_path(@book.id), class:"show_#{@book.id}" %>
|
<a href="/books" class="back">Back</a>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
<% end %>
<p><strong>Title:</strong><span><%= @book.title %></span></p>
<p><strong>Body:</strong><span><%= @book.body %></span></p>

<%= link_to 'Edit', edit_path(@book.id), class:"edit_#{@book.id}" %>
|
<a href="/books" class="back">Back</a>

app/views/books/top.html.erb
<h1>Books</h1>
<% if flash[:notice] && flash[:notice] == "削除成功!" %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
<% end %>
<table>
  <tr>
    <th>Title</th><th>Body</th>
  </tr>
  <!-- @booksが空だとエラーが表示されるためif -->
  <% if @books %>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td><td><%= book.body %></td>
      <td>
        <%= link_to 'Show', show_path(book.id), class:"show_#{book.id}" %>
        <%= link_to 'Edit', edit_path(book.id), class:"edit_#{book.id}" %>
        <!-- confirmはポップアップ機能の追加 -->
        <%= link_to 'Destroy', destroy_path(book.id), method: :'delete', data: {confirm: '削除ええんか？'}, class:"destroy_#{book.id}" %>
      </td>
    </tr>
    <% end %>
  <% end %>
</table>


<h1>New book</h1>
<% if flash[:notice] && flash[:notice] != "削除成功!" %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
<% end %>
<%= form_for(@book, url: {action: "create"}, method: :post) do |f| %>
  <!-- バリデーションエラーを表示させる -->
  <% if @book.errors.any? %>
    <p>入力した内容にエラーが<%= @book.errors.count %>件あります</p>
    <ul>
      <% @book.errors.full_messages.each do |book_error| %>
        <li><%= book_error %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :title, "title" %>
  <%= f.text_field :title, class:"book_title" %>

  <%= f.label :body, "Body" %>
  <%= f.text_area :body, class:"book_body" %>

  <%= f.submit 'Create Book' %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/toppage/top.html.erb
<h1>ようこそBookersへ！</h1>
<p>
  <strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や<br>
  印象を共有し交換することができます
</p>
<a href="books">start</a>